apiVersion: v1
kind: Service
metadata:
  name: k8s-wrangler-service
spec:
  selector:
    app: k8s-wrangler
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-wrangler
spec:
  selector:
    matchLabels:
      app: k8s-wrangler
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-wrangler
    spec:
      containers:
      - name: k8s-wrangler
        image: k8s-wrangler:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
