---
apiVersion: v1
kind: Namespace
metadata:
  name: chipy
  labels:
    name: chipy

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: k8s-wrangler-service
#   namespace: chipy
# spec:
#   selector:
#     app: k8s-wrangler
#   ports:
#   - protocol: "TCP"
#     port: 5000
#     targetPort: 5000
#   type: LoadBalancer

---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: k8s-wrangler-read-only
    namespace: chipy
  rules:
  # this works with k8s v1.14.0
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["list"]
  # this works with k8s v1.16.0+
  # - apiGroups: ["apps"]
  #   resources: ["deployments"]
  #   verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: ks8-wrangler-read-only
    namespace: chipy
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: chipy
  roleRef:
    kind: ClusterRole
    name: k8s-wrangler-read-only
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-wrangler
  namespace: chipy
spec:
  selector:
    matchLabels:
      app: k8s-wrangler
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-wrangler
    spec:
      containers:
      - name: k8s-wrangler
        image: k8s-wrangler:1.14.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
